config/routes.rb
Clu2::Application.routes.draw do

  namespace :crm do
    resources :health_infos
  end

  resources :underwriting do
    collection do
      get 'ask'
      get 'guides'
      get 'questionnaires'
      get 'table_shave'
      get 'xrae'
    end
  end

  resources :sales_tools do
    collection do
      get 'calculators'
      get 'contracting'
      get 'planning'
      get 'productivity'
      get 'quoters'
      get 'training'
    end
  end

  resources :help do
    collection do
      get 'faq'
      get 'tutorials'
      get 'about'
      get 'suggestions'
      post 'post_suggestion'
    end
  end

  match "/login", :controller => "usage/user_sessions", :action => "new"
  match "/logout", :controller => "usage/user_sessions", :action => "destroy", :via => [:get, :delete]
  match "/signup", :controller => "usage/users", :action => "new"
  match "/tagging/tag_keys/home", :controller => "tagging/tag_keys", :action => "home"
  match "/new_connection_spouse", :controller => "crm/connections", :action => "new_connection_spouse"
  # TOP-LEVEL RESOURCES

  resources :address

  resources :contact_info

  resources :email_address

  resources :leads do
    collection {
      get 'diag'
      post 'diag'
    }
  end

  resources :website

  resources :home do
    collection do
      get 'get_states'
      put 'update_contact_info'
      get 'get_gender'
    end
  end

  resources :phone do
    collection do
      get 'get_phone_type'
    end
  end

  # NAMESPACES

  resources :email_address

  resources :contact_info

  namespace :usage do
    resources :notes
    resource :user_sessions, :only => [:new, :create, :destroy]

    resources :users, :only => [:new, :create, :update] do
      collection do
        get 'personal'
        post 'update_attribute'
        get 'autocomplete_users_first_name'
        get 'assign_agent'
        get 'permissions'
        get 'lead_distribution_rules'
        put 'assign_profile'
        get 'assign_profile_model'
        get 'tasks'
        get 'incomplete_tasks'
        get 'completed_tasks'
      end

      member do
        put 'update_agent_field_set'
        put "update_password"
      end

    end
    resources :lead_distribution_weights, :only => [:index, :update]
    resources :password_resets
    resources :profiles do
      collection do
        post 'select'
        put 'assign_profile'
        put 'remove_profile'
      end
    end
    resources :contracts
    resources :licenses
  end

  namespace :crm do

    resources :beneficiaries do
      collection do
        post 'update_attributes'
        post 'update_percentages'
      end
    end

    resources :financial_infos

    resources :activities do
      collection do
        get 'all_activity_statuses'
        get 'activities_between_dates'
      end
    end

    resources :notes

    get "status_types/index"

    get "status_types/new"

    post "status_types/create"

    get "status_types/edit"

    put "status_types/update"

    resources :auto_system_task_rules, :only => [:new, :create, :index]

    resources :cases do
      collection do
        get 'index'
        get 'prospects'
        get 'leads'
        get 'book_of_business'
        get 'details'
        get 'requirements'
        get 'owner'
        get 'exam_completion'
        get 'quoter_completion'
        get 'follow_up'
        get 'exam'
        get 'autocomplete_carrier_name'
        post 'update_details_attribute'
        post 'update_quote_param'
        get 'get_policy_types'
        post 'update_agent'
        post 'owners_update'
        post 'owner_contact_info_update'
        get 'get_owner_beneficiary_type'
      end
      member do
        get 'ezlink'
      end
    end

    resources :connections do
      collection do
        get 'health_completion'
        get 'personal_completion'
        get 'connection_summary'
        get 'connection_tags'
        get 'personal'
        get 'destroy_connection_tag'
        get 'prospects'
        get 'contacts'
        get 'get_marrital_statuses'
        get 'get_citizenships'
        post 'update_agent'
        get 'add_spouse'
        get 'autocomplete_connections_first_name'
        get 'financial'
        post 'financial_info_update'
        post 'connection_info_update'
        post 'contact_info_update'
        get 'tracking'
        get 'get_connection_types'
      end
      member do
        get 'financial'
        get 'health'
        get 'personal'
        get 'tracking'
      end
    end
    resources :spouses
    resources :statuses

    resources :system_tasks do
      collection do
        get 'dashboard'
        get 'cases_current_status_system_tasks'
        get 'sidebar'
      end
    end

  end

  namespace :marketing do
    get "campaigns/edit"
    get "campaigns/destroy"
    get "marketing_base/links"
    resources :campaigns

    get 'auto_task_rules/destroy'
    resources :auto_task_rules do
      collection do
        get 'autocomplete_marketing_campaigns_name'
        get 'autocomplete_auto_system_task_rules_name'
        get 'edit'
      end
    end

    resources :memberships do
      collection do
        get 'autocomplete_usage_user_first_name'
        get 'membership_templates'
      end
    end

    namespace :email do
      resources :templates do
        collection do
          get 'autocomplete_marketing_email_templates_name'
          get 'template_liquid_options'
          get 'clone_template'
        end
      end

      resources :messages do
        member do
          post 'send_message'
        end
      end

      resources :smtp_servers
    end

    namespace :snail_mail do
      resources :templates do
        collection do
          get 'autocomplete_marketing_snail_mail_templates_name'
          get 'template_liquid_options'
        end
      end
      resources :messages
    end

  end

  namespace :quoting do

    resources :quotes do
      collection { post 'bypass_health_analyzer' }
      member { get 'results' }
    end
    resources :leads do
      collection {
        get 'new_quote'
        post 'create_quote'
      }
    end
  end

  namespace :reporting do
    resources :memberships do
      collection do
        get 'autocomplete_usage_user_first_name'
      end
    end

    resources :searches do
      member do
        get 'results'
      end
      collection do
         get 'legacy_new'
         get 'legacy_edit'
         put 'legacy_update'
         get 'legacy_update'
         get 'legacy_index'
         post 'legacy_results'
         get 'legacy_results'
         get 'autocomplete_usage_user_login'
         get 'autocomplete_usage_role_name'
         get 'autocomplete_usage_user_first_name'
         get 'search_policy_create_date'
      end
    end
  end

  namespace :tagging do
    resources :tag_keys do
      member do
        get 'home'
      end
     end

     resources :memberships do
       collection do
         get 'autocomplete_usage_user_first_name'
       end
     end

    resources :tags do
      collection do
        post 'search'
        post 'create_multiple'
      end
     end
  end

  namespace :usage do
    resource :user_sessions, :only => [:new, :create, :destroy]
    resources :users, :only => [:new, :create, :update, :index] do
      collection do
        get 'personal'
        post 'update_attribute'
        get 'autocomplete_users_first_name'
        get 'assign_agent'
        get 'permissions'
        get 'lead_distribution_rules'
        post 'update_permissions'
        get 'search_users'
        get 'search_agency_users'
        get 'l_and_c'
        get 'memberships'
        post 'update_aml_vendor'
        post 'update_usage_license'
        get 'impersonate'
        get 'end_impersonate'
      end

      member do
        put 'update_agent_field_set'
      end

    end
    resources :lead_distribution_weights, :only => [:index, :update]
    resources :password_resets
    resources :profiles, only: [] do
      collection {post 'select'}
    end
    resources :contracts do
      collection do
        get 'autocomplete_usage_aml_vendor_name'
      end
    end
    resources :licenses do
      collection do
        get 'autocomplete_usage_user_first_name'
      end
    end
    get "staff_assignment/index"
    resources :staff_assignment do
      member do
        get 'new'
  get 'autocomplete_usage_user_first_name'
      end
      collection do
        post 'create'
     end
    end
   end
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

end

app/models/tagging.rb
module Tagging
  def self.table_name_prefix
    'tagging_'
  end
end

app/models/tagging/auto_tag_rule.rb
class Tagging::AutoTagRule < ActiveRecord::Base
   attr_accessible :auto_tag_rule_set_id, :connection_pattern_id, :tag_key_id, :tag_value_id, 
                  :use_pattern_id
                   
   # Associations
   belongs_to :auto_tag_rule_set, :class_name => "Tagging::AutoTagRuleSet"
   belongs_to :connection_pattern, :class_name => "Crm::Pattern"
   belongs_to :tag_key, :class_name => "Tagging::TagKey"
   belongs_to :tag_value, :class_name => "Tagging::TagValue"
   belongs_to :user_pattern, :class_name => "Usage::Pattern"
end

app/models/tagging/auto_tag_rule_set.rb
class Tagging::AutoTagRuleSet < ActiveRecord::Base
  attr_accessible :name, :auto_tag_rule_id, :tag_key_id, :tag_value_id
  
  # Associations
   belongs_to :auto_tag_rule_set, :class_name => "Tagging::AutoTagRule"
   belongs_to :tag_key, :class_name => "Tagging::TagKey"
   belongs_to :tag_value, :class_name => "Tagging::TagValue"
end

app/models/tagging/membership.rb
class Tagging::Membership < ActiveRecord::Base
  attr_accessible :custom_tags_privilege, :owner_id, :ownership_id, :ownership_name
  attr_accessor :ownership_name
  
  # Associations
  belongs_to :owner, :foreign_key => :owner_id, :class_name => "Usage::User"
  belongs_to :ownership, :class_name => "Ownership"

end

app/models/tagging/tag_key.rb
class Tagging::TagKey < ActiveRecord::Base
  attr_accessible :name
  attr_accessible :owner_id, :owner, :ownership, :ownership_id

  validates :name, uniqueness:true

  # Associations
  has_and_belongs_to_many :saved_searches
  has_many :tag_assignment_rules
  has_many :tags, class_name: "Tagging::Tag"
  has_many :tag_values, :through => :tags
  belongs_to :auto_tag_rule_set, :class_name => "Tagging::AutoTagRuleSet"
  belongs_to :owner, class_name: "Usage::User"
  belongs_to :ownership
  belongs_to :user, class_name: "Usage::User"
  belongs_to :crm_connection, class_name: 'Crm::Connection', :foreign_key => :connection_id

  def get_commom_tags_for_user(user_id)
     user = Usage::User.find(params[:user_id])
     tags = user.tags
  end

  def self.search(search)
    if search
      where('name like ?', "%#{search}%")
    end
  end
end

app/models/tagging/tag_rule_field.rb
class Tagging::TagRuleField < ActiveRecord::Base
  attr_accessible :name
end

app/models/tagging/tag_rule_operator.rb
class Tagging::TagRuleOperator < CluEnum
  self.table_name = 'tagging_tag_rule_operators'
  self.primary_key = :id
  attr_accessible :name
end

app/models/tagging/tag_rule_type.rb
class Tagging::TagRuleType < ActiveRecord::Base
  attr_accessible :name
end

app/models/tagging/tag_type.rb
class Tagging::TagType < CluEnum
  self.table_name = 'tagging_tag_types'
  self.primary_key = :id
  attr_accessible :name

  has_many :tags, class_name: "Tagging::Tag"
end

app/controllers/tagging/memberships_controller.rb
class Tagging::MembershipsController < ApplicationController

  before_filter :require_super, :only => :index
  autocomplete :usage_user, :first_name, :class_name => "Usage::User"
  
  def index
    @tagging_memberships = Tagging::Membership.all

    respond_to do |format|
      format.js {render :layout => false} 
    end
  end
  
  def show
    @tagging_membership = Tagging::Membership.find(params[:id])

    respond_to do |format|
      format.js {render :layout => false} 
    end
  end

  def new
    @tagging_membership = Tagging::Membership.new
    @ownerships = Ownership.all
     
    respond_to do |format|
      format.js {render :layout => false} 
    end
  end
  
  def edit
    @tagging_membership = Tagging::Membership.find(params[:id])
    
    respond_to do |format|
      format.js {render :layout => false} 
    end
  end
  
  def create
    @tagging_membership = Tagging::Membership.new(params[:tagging_membership])
    @tagging_membership.save

    respond_to do |format|
      if @tagging_membership.save
         @tagging_membership = Tagging::Membership.new
         @ownerships = Ownership.all
        format.js {render :layout => false} 
      else
        format.js { render action: "new" }
      end
    end
  end

  def update
    @tagging_membership = Tagging::Membership.find(params[:id])
    @tagging_memberships = Tagging::Membership.all
    
    respond_to do |format|
      if @tagging_membership.update_attributes(params[:tagging_membership])
         @tagging_membership = Tagging::Membership.new
        format.js {render :layout => false} 
      else
        format.js { render action: "edit" }
      end
    end
  end
  
  def destroy
    @tagging_membership = Tagging::Membership.find(params[:id])
    @tagging_membership.destroy
    @tagging_memberships = Tagging::Membership.all

    respond_to do |format|
      format.js {render :layout => false} 
    end
  end
end

app/controllers/tagging/tag_keys_controller.rb
class Tagging::TagKeysController < ApplicationController
  
  def index
    if !params[:user_id].blank?
      user = Usage::User.find(params[:user_id])
      @tags = user.tags
    elsif params[:connection_id]
      connection = Crm::Connection.find(params[:connection_id])
      @tags = connection.tags
    end
    respond_to do | format |  
      format.js {render :layout => false}  
    end
  end
  
  def home
    
  end
  
  def new
    @tag_key = Tagging::TagKey.new
    @ownerships = Ownership.all
    respond_to do | format |  
      format.js {render :layout => false}  
    end
  end
  
  def create
    tag_key = Tagging::TagKey.create(params[:tagging_tag_key])
    tag_key.owner_id = current_user.id
    tag_key.save
    @tag_keys = Tagging::TagKey.all
  end
  
  def edit
    @tag_key = Tagging::TagKey.find(params[:id])
    @ownerships = Ownership.all
    respond_to do | format |  
      format.js {render :layout => false}  
    end
  end
  
  def update
    @tag_key = Tagging::TagKey.find(params[:id])
    if @tag_key.update_attributes(params[:tagging_tag_key])  
        @tag_keys = Tagging::TagKey.all
         respond_to do | format |  
          format.js {render :layout => false}
         end
      end
  end
end

app/controllers/tagging/tags_controller.rb
class Tagging::TagsController < ApplicationController

  def index
    if !params[:user_id].blank?
      user = Usage::User.find(params[:user_id])
      @recent_tags = Tagging::Tag.get_recent_tags_for_user(user)
      @system_tags = Tagging::Tag.get_system_tags_for_user(user)
      @custom_tags = Tagging::Tag.get_custom_tags_for_user(user)
      @recommended_tags = user.tag_keys.find(:all, :order => "tagging_tag_keys.created_at desc", :limit => 10)
    elsif params[:connection_id]
      connection = Crm::Connection.find(params[:connection_id])
      @recent_tags = Tagging::Tag.get_recent_tags_for_user(connection)
      @system_tags = Tagging::Tag.get_system_tags_for_user(connection)
      @custom_tags = Tagging::Tag.get_custom_tags_for_user(connection)
      @recommended_tags = connection.tag_keys.find(:all, :order => "tagging_tag_keys.created_at desc", :limit => 10)
    end
    respond_to do | format |
      format.js {
        @container_to_be_replaced = container_to_be_used(params[:container_id])
        render :layout => false
      }
    end
  end

  def new
    @tag_types = Tagging::TagType.all
    @tag = Tagging::Tag.new
  end

  def create_multiple
    connection_ids = params[:connection_id].split(",").uniq unless params[:connection_id].blank?
    connection_ids.each do |connection_id|
      connection = Crm::Connection.find(params[:connection_id])
      Tagging::Tag.create_from_string(params[:tag_name], connection)
    end
    render :text => ''
  end

  def create
    unless params[:tag_name].blank?
      connection = Crm::Connection.find(params[:connection_id])
      Tagging::Tag.create_from_string(params[:tag_name], connection)
      if !params[:user_id].blank?
        user = Usage::User.find(params[:user_id])
        @tags = user.tags
        @recent_tags = user.tag_keys.find(:all, :order => "tagging_tag_keys.created_at desc", :limit => 5)
        @recommended_tags = user.tag_keys.find(:all, :order => "tagging_tag_keys.created_at desc", :limit => 10)
      elsif params[:connection_id]
        connection = Crm::Connection.find(params[:connection_id])
        @tags = connection.tags
        @recent_tags = connection.tag_keys.find(:all, :order => "tagging_tag_keys.created_at desc", :limit => 5)
        @recommended_tags = connection.tag_keys.find(:all, :order => "tagging_tag_keys.created_at desc", :limit => 10)
      end
    end
  end

  def search
    @search_tags = Tagging::TagKey.search(params[:search_tag])
    @tags = @search_tags
  end
end

app/helpers/tagging/memberships_helper.rb
module Tagging::MembershipsHelper
end

app/helpers/tagging/tag_keys_helper.rb
module Tagging::TagKeysHelper
end

app/helpers/tagging/tags_helper.rb
module Tagging::TagsHelper
end

app/views/tagging/tags/_form.html.erb
<table style="width:80%">
  <tr class="field">
      <td style="width:10%"></td>
      <td>Tag Value:</td>
      <td><%= text_field_tag "tag_name" %></td>
  </tr>
  <tr class="field">
      <td style="width:10%"></td>
      <td></td>
      <td>
        <% if !params[:user_id].blank? %>
          <%= hidden_field_tag "user_id", params[:user_id] %>
        <% else %>
          <%= hidden_field_tag "connection_id", params[:connection_id] %>
        <% end %>
      </td>
  </tr>
  <tr>
      <td style="width:10%"></td>
      <td></td>
      <td class="actions"><%= submit_tag 'Save tag', :onclick => "$('#container-for-tagging-tags').modal('hide')" %></td>
  </tr>
</table>

app/views/tagging/tags/_index.html.erb
<% unless params[:connection_summary] %>
  <%= render :partial => "shared/tab/agency_management", :locals => {:tab => "tagging"} %>
<% end %>

<style type="text/css">
#ul
  {
      padding:0;
            margin:0;
            list-style-type:none;
            font-size:12px;
            color:#717171;
            width:100%;
}
#ul li
  {
      border-bottom:0px solid #eeeeee;
            padding:10px 0px 10px 20px;
            color: #000;
  }
#ul li b
  {
   color:#000;
  }
</style>
<div style="background:#fff;">
  <div class="row title-row">
   <div class="navbar-inner"><h4 class="title system-management-row">Tags&nbsp;<i class="icon-tag"></i>
    <%= form_tag search_tagging_tags_path, :remote => true, :style => "float: right; margin-right: 10px; width: 280px;" do %>
      <div style="margin-bottom: 0px;" class="input-prepend">
        <span class="add-on"><i class="icon-tag"></i></span>
        <%= text_field_tag "search_tag", nil, {:class => "span9", :id => "prependedInput", :placeholder => "Search...."} %>
        <%= hidden_field_tag "connection_id", params[:connection_id] %>
        <%= hidden_field_tag "user_id", params[:user_id] %>
        <%= submit_tag "go", :class => "btn btn-primary", :style => "float: right;", :id => "submit"%>
      </div>
    </h4>
    <% end %>
  </div>
</div>
  <div style="height:40px; float-top:0px;"></div>
  <div style=" width:3%; height:250px; float:left;"></div>
  <div style="margin-bottom: 20px; color:#000; width:20%; height:300px; float:left; border: 1px solid #B7B7B7;border-radius: 8px 8px 8px 8px; overflow: auto;">
     <ul id="ul" style="list-style-type:none; font-size:12px; color:#717171; width:100%;">
       <li style="text-align: center; padding-left: 0px;"><b>Common Tags</b></li>
             <li class="icon-tag">&nbsp; Referred by jeff Rose</li><br />
             <li class="icon-tag">&nbsp; Referred by Bill Gates</li><br />
             <li class="icon-tag">&nbsp; Referred by WSI</li><br />
             <li class="icon-tag">&nbsp; 5 Member Home</li><br />
             <li class="icon-tag">&nbsp; Likes Cheesecake</li><br />
        </ul>
    <ul id="ul">
      <li style="text-align: center; padding-left: 0px;"><b>Recent Tags</b></li>
      <% @recent_tags.each do |recent_tag| %>
        <li class="icon-tag">&nbsp; <%= recent_tag.to_s %></li><br />
      <% end %>
        </ul>
  </div>
  <div style=" width:3%; height:250px; float:left;"></div>
  <div style=" color:#000; width:20%; height:300px; float:left; border: 1px solid #B7B7B7;border-radius: 8px 8px 8px 8px; overflow: auto;">
     <ul id="ul">
       <li style="text-align: center; padding-left: 0px;"><b>Recommended Tags</b></li>
        <% @recommended_tags.each do |common_tag| %>
        <li class="icon-tag">&nbsp; <%= common_tag.name %></li><br />
      <% end %>
        </ul>
  </div>
  <div style="width:2%; height:300px; float:left;"></div>
  <div id="search_tags" style=" float:left; height:100%; color:#000">
    <%= render :partial => "search" %>
  </div>
  <div style=" color:#000; width:20%; height:300px; margin-right: 10px; float:right; border: 1px solid #B7B7B7;border-radius: 8px 8px 8px 8px; overflow: auto;">
     <ul id="ul">
       <li style="text-align: center; padding-left: 0px;"><b>Custom Tags</b></li>
             <% @custom_tags.each do |custom_tag| %>
         <li class="icon-tag">&nbsp; <%= custom_tag.to_s %></li><br />
      <% end %>
        </ul>
    <ul id="ul">
      <li style="text-align: center; padding-left: 0px;"><b>System Tags</b></li>
             <% @system_tags.each do |system_tag| %>
         <li class="icon-tag">&nbsp; <%= system_tag.to_s %></li><br />
      <% end %>
        </ul>
  </div>
  <div style="width:3%; height:300px; float:right; border-left: 3px solid #B7B7B7;"></div>
</div>

app/views/tagging/tags/_new.html.erb
<table class="table table-condensed">
	<tr>
	  <th colspan="8">Add New Tag<br/><hr/><th>
	</tr>
</table>

<%= render 'form' %>

app/views/tagging/tags/_search.html.erb
<b>Search Results For "<%= params[:search_tag] %>"</b><br />
<% if @search_tags.blank?%>
  <i>Nothing found</i>
<% else %>
  	<% @search_tags.each do |search_tag| %>
	  <li class="icon-tag">&nbsp <%= search_tag.name %></li><br />
	<% end %>
<% end %>

app/views/tagging/tags/create.html.erb
<h1>Crm::AutoSystemTaskRules#create</h1>
<p>Find me in app/views/crm/auto_system_task_rules/create.html.erb</p>

app/views/tagging/tags/create.js.erb
$( "#main-container" ).html( "<%= escape_javascript( render( :partial => "index" ) ) %>" );

app/views/tagging/tags/index.js.erb
$( "#<%=@container_to_be_replaced%>" ).html( "<%= escape_javascript( render( :partial => "index" ) ) %>" );

app/views/tagging/tags/new.js.erb
$( "#tag_keys" ).html( "<%= escape_javascript( render( :partial => "new" ) ) %>" );

app/views/tagging/tags/search.js.erb
$( "#search_tags" ).html( "<%= escape_javascript( render( :partial => "search" ) ) %>" );