config/routes.rb
Clu2::Application.routes.draw do

  namespace :crm do
    resources :health_infos
  end

  resources :underwriting do
    collection do
      get 'ask'
      get 'guides'
      get 'questionnaires'
      get 'table_shave'
      get 'xrae'
    end
  end

  resources :sales_tools do
    collection do
      get 'calculators'
      get 'contracting'
      get 'planning'
      get 'productivity'
      get 'quoters'
      get 'training'
    end
  end

  resources :help do
    collection do
      get 'faq'
      get 'tutorials'
      get 'about'
      get 'suggestions'
      post 'post_suggestion'
    end
  end

  match "/login", :controller => "usage/user_sessions", :action => "new"
  match "/logout", :controller => "usage/user_sessions", :action => "destroy", :via => [:get, :delete]
  match "/signup", :controller => "usage/users", :action => "new"
  match "/tagging/tag_keys/home", :controller => "tagging/tag_keys", :action => "home"
  match "/new_connection_spouse", :controller => "crm/connections", :action => "new_connection_spouse"
  # TOP-LEVEL RESOURCES

  resources :address

  resources :contact_info

  resources :email_address

  resources :leads do
    collection {
      get 'diag'
      post 'diag'
    }
  end

  resources :website

  resources :home do
    collection do
      get 'get_states'
      put 'update_contact_info'
      get 'get_gender'
    end
  end

  resources :phone do
    collection do
      get 'get_phone_type'
    end
  end

  # NAMESPACES

  resources :email_address

  resources :contact_info

  namespace :usage do
    resources :notes
    resource :user_sessions, :only => [:new, :create, :destroy]

    resources :users, :only => [:new, :create, :update] do
      collection do
        get 'personal'
        post 'update_attribute'
        get 'autocomplete_users_first_name'
        get 'assign_agent'
        get 'permissions'
        get 'lead_distribution_rules'
        put 'assign_profile'
        get 'assign_profile_model'
        get 'tasks'
        get 'incomplete_tasks'
        get 'completed_tasks'
      end

      member do
        put 'update_agent_field_set'
        put "update_password"
      end

    end
    resources :lead_distribution_weights, :only => [:index, :update]
    resources :password_resets
    resources :profiles do
      collection do
        post 'select'
        put 'assign_profile'
        put 'remove_profile'
      end
    end
    resources :contracts
    resources :licenses
  end

  namespace :crm do

    resources :beneficiaries do
      collection do
        post 'update_attributes'
        post 'update_percentages'
      end
    end

    resources :financial_infos

    resources :activities do
      collection do
        get 'all_activity_statuses'
        get 'activities_between_dates'
      end
    end

    resources :notes

    get "status_types/index"

    get "status_types/new"

    post "status_types/create"

    get "status_types/edit"

    put "status_types/update"

    resources :auto_system_task_rules, :only => [:new, :create, :index]

    resources :cases do
      collection do
        get 'index'
        get 'prospects'
        get 'leads'
        get 'book_of_business'
        get 'details'
        get 'requirements'
        get 'owner'
        get 'exam_completion'
        get 'quoter_completion'
        get 'follow_up'
        get 'exam'
        get 'autocomplete_carrier_name'
        post 'update_details_attribute'
        post 'update_quote_param'
        get 'get_policy_types'
        post 'update_agent'
        post 'owners_update'
        post 'owner_contact_info_update'
        get 'get_owner_beneficiary_type'
      end
      member do
        get 'ezlink'
      end
    end

    resources :connections do
      collection do
        get 'health_completion'
        get 'personal_completion'
        get 'connection_summary'
        get 'connection_tags'
        get 'personal'
        get 'destroy_connection_tag'
        get 'prospects'
        get 'contacts'
        get 'get_marrital_statuses'
        get 'get_citizenships'
        post 'update_agent'
        get 'add_spouse'
        get 'autocomplete_connections_first_name'
        get 'financial'
        post 'financial_info_update'
        post 'connection_info_update'
        post 'contact_info_update'
        get 'tracking'
        get 'get_connection_types'
      end
      member do
        get 'financial'
        get 'health'
        get 'personal'
        get 'tracking'
      end
    end
    resources :spouses
    resources :statuses

    resources :system_tasks do
      collection do
        get 'dashboard'
        get 'cases_current_status_system_tasks'
        get 'sidebar'
      end
    end

  end

  namespace :marketing do
    get "campaigns/edit"
    get "campaigns/destroy"
    get "marketing_base/links"
    resources :campaigns

    get 'auto_task_rules/destroy'
    resources :auto_task_rules do
      collection do
        get 'autocomplete_marketing_campaigns_name'
        get 'autocomplete_auto_system_task_rules_name'
        get 'edit'
      end
    end

    resources :memberships do
      collection do
        get 'autocomplete_usage_user_first_name'
        get 'membership_templates'
      end
    end

    namespace :email do
      resources :templates do
        collection do
          get 'autocomplete_marketing_email_templates_name'
          get 'template_liquid_options'
          get 'clone_template'
        end
      end

      resources :messages do
        member do
          post 'send_message'
        end
      end

      resources :smtp_servers
    end

    namespace :snail_mail do
      resources :templates do
        collection do
          get 'autocomplete_marketing_snail_mail_templates_name'
          get 'template_liquid_options'
        end
      end
      resources :messages
    end

  end

  namespace :quoting do

    resources :quotes do
      collection { post 'bypass_health_analyzer' }
      member { get 'results' }
    end
    resources :leads do
      collection {
        get 'new_quote'
        post 'create_quote'
      }
    end
  end

  namespace :reporting do
    resources :memberships do
      collection do
        get 'autocomplete_usage_user_first_name'
      end
    end

    resources :searches do
      member do
        get 'results'
      end
      collection do
         get 'legacy_new'
         get 'legacy_edit'
         put 'legacy_update'
         get 'legacy_update'
         get 'legacy_index'
         post 'legacy_results'
         get 'legacy_results'
         get 'autocomplete_usage_user_login'
         get 'autocomplete_usage_role_name'
         get 'autocomplete_usage_user_first_name'
         get 'search_policy_create_date'
      end
    end
  end

  namespace :tagging do
    resources :tag_keys do
      member do
        get 'home'
      end
     end

     resources :memberships do
       collection do
         get 'autocomplete_usage_user_first_name'
       end
     end

    resources :tags do
      collection do
        post 'search'
        post 'create_multiple'
      end
     end
  end

  namespace :usage do
    resource :user_sessions, :only => [:new, :create, :destroy]
    resources :users, :only => [:new, :create, :update, :index] do
      collection do
        get 'personal'
        post 'update_attribute'
        get 'autocomplete_users_first_name'
        get 'assign_agent'
        get 'permissions'
        get 'lead_distribution_rules'
        post 'update_permissions'
        get 'search_users'
        get 'search_agency_users'
        get 'l_and_c'
        get 'memberships'
        post 'update_aml_vendor'
        post 'update_usage_license'
        get 'impersonate'
        get 'end_impersonate'
      end

      member do
        put 'update_agent_field_set'
      end

    end
    resources :lead_distribution_weights, :only => [:index, :update]
    resources :password_resets
    resources :profiles, only: [] do
      collection {post 'select'}
    end
    resources :contracts do
      collection do
        get 'autocomplete_usage_aml_vendor_name'
      end
    end
    resources :licenses do
      collection do
        get 'autocomplete_usage_user_first_name'
      end
    end
    get "staff_assignment/index"
    resources :staff_assignment do
      member do
        get 'new'
  get 'autocomplete_usage_user_first_name'
      end
      collection do
        post 'create'
     end
    end
   end
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'home#index'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'

end

app/models/usage.rb
module Usage
  def self.table_name_prefix
    'usage_'
  end
end

app/models/usage/agent_field_set.rb
class Usage::AgentFieldSet < ActiveRecord::Base
  attr_accessible :premium_limit, :temporary_suspension, :tz_max, :tz_min, :aml_id

  # Associations
  has_one :user
  has_many :licenses
  has_many :contracts
  belongs_to :aml, :class_name => "Usage::Aml"
end

app/models/usage/aml.rb
class Usage::Aml < ActiveRecord::Base
  attr_accessible :completion, :vendor_id
  
  has_many :agent_field_set, :class_name => "Usage::AgentFieldSet", :foreign_key => :aml_id
  belongs_to :aml_vendor, :class_name => "Usage::AmlVendor"
end

app/models/usage/aml_vendor.rb
class Usage::AmlVendor < ActiveRecord::Base
  attr_accessible :name, :aml_vendor, :contracts_attributes, :aml_attributes
  
  # Associations
  has_many :contracts
  has_many :aml, :class_name => "Usage::Aml", :foreign_key => :vendor_id
  
 
  accepts_nested_attributes_for :contracts, :allow_destroy => true
  accepts_nested_attributes_for :aml, :allow_destroy => true
  
end

app/models/usage/ascendent_association.rb
class Usage::AscendentAssociation < ActiveRecord::Base
  self.table_name = 'usage_ascendents_descendents'
  belongs_to :ascendent, class_name: 'Usage::User'
  belongs_to :descendent, class_name: 'Usage::User'
end

app/models/usage/commission_level.rb
class Usage::CommissionLevel < CluEnum
  self.table_name = 'usage_commission_levels'
  self.primary_key = :id
  attr_accessible :name

  # Associations
  has_many :users, class_name: "Usage::User", :foreign_key => "commission_level_id"

end

app/models/usage/contract.rb
class Usage::Contract < ActiveRecord::Base
  attr_accessible :carrier_id, :status_id, :user, :carrier, :state,
                  :aml_vendor_id, :carrier_contract_id, :state_id,
                  :corporate, :effective_date, :expiration, :agent_field_set_id, :appointment
 
  #validates_presence_of :state_id
  # Associations
  belongs_to :agent_field_set
  belongs_to :user
  belongs_to :carrier, :class_name => "Carrier"
  belongs_to :aml_vendor, :class_name => "Usage::AmlVendor"
  belongs_to :status, :class_name => "Usage::ContractStatus"
  belongs_to :state, class_name: "State"
  
  accepts_nested_attributes_for :aml_vendor, :allow_destroy => true
  
  validate :check_agent_license
  
  private 
  
  def check_agent_license
   if self.agent_field_set.licenses.where("state_id = #{self.state_id}").blank?
     errors.add(:state_id, "Agent not have license")
   end
    
  end
  
end

app/models/usage/contract_status.rb
class Usage::ContractStatus < CluEnum
  self.table_name = 'usage_contract_statuses'
  self.primary_key = :id
  attr_accessible :value
end

app/models/usage/lead_distribution.rb
class Usage::LeadDistribution < ActiveRecord::Base
  
  attr_accessible :agent_id, :count, :date
  
  # Associations
  belongs_to :agent, :foreign_key => :agent_id, :class_name => "Usage::User"
  
end

app/models/usage/lead_distribution_weight.rb
class Usage::LeadDistributionWeight < ActiveRecord::Base
  attr_accessible :agent_id, :tag_value_id, :weight, :premium_limit, :countdown, :lock_version,
                  :tag_value
  
  # Associations
  belongs_to :agent, :foreign_key => :agent_id, :class_name => "Usage::User"

  belongs_to :tag_value, :foreign_key => :tag_value_id, :class_name=> "Tagging::TagValue"

  attr_accessor :attempts_to_crement_countdown
  
  def decrement_countdown!
    self.countdown = self.countdown - 1
    save
  rescue ActiveRecord::StaleObjectError
    attempts_to_crement_countdown ||= 0
    attempts_to_crement_countdown += 1
    unless attempts_to_crement_countdown > 5
      self.decrement_countdown!
    else
      false
    end
  ensure
    # increment siblings' countdowns for this lead type if countdown has reached (or passed) 0
    if self.countdown < 1
      self.class.increment_countdowns(agent.parent_id, tag_value_id)
    end
  end
  
  def increment_countdown!
    self.countdown = self.countdown + self.weight
    save
  rescue ActiveRecord::StaleObjectError
    attempts_to_crement_countdown ||= 0
    attempts_to_crement_countdown += 1
    unless attempts_to_crement_countdown > 5
      self.increment_countdown! 
    else
      false
    end
  end

  def self.increment_countdowns parent_id, lead_type_id
    if lead_type_id.present?
      joins(:agent)
      .where("#{reflect_on_association(:agent).table_name}.parent_id = ?", parent_id)
      .where(tag_value_id:lead_type_id)
      .all(readonly:false).each { |weight|
        weight.increment_countdown!
      }
    end
  end

end

app/models/usage/license.rb
class Usage::License < ActiveRecord::Base
  attr_accessible :agent_field_set, :agent_field_set_id,
                  :expiration, :expiration_warning_sent, :number, :status_id, :home, :p_and_c,
                  :state_id, :user_id, :user, :state, :corporate, :effective_date, :user_name,
                  :vehicle, :life, :agent_field_set_id
                  
  attr_accessor :user_name 
                  
  validates_presence_of :agent_field_set_id, :state_id, :number
  validates_uniqueness_of :state_id, :scope => [:agent_field_set_id]
  # Associations
  belongs_to :user
  belongs_to :agent_field_set
  belongs_to :state, class_name: "State"
  belongs_to :status, class_name: "Usage::LicenseStatus"
  
  
end

app/models/usage/license_status.rb
class Usage::LicenseStatus < CluEnum
  self.table_name = 'usage_license_statuses'
  self.primary_key = :id
  attr_accessible :value
end

app/models/usage/note.rb
class Usage::Note < ActiveRecord::Base
  attr_accessible :body, :creator_id, :user_id, :user
  
  validates_presence_of :body, :user
  # Association
  belongs_to :user, :class_name => "Usage::User"
  belongs_to :creator, :foreign_key => :creator_id, :class_name => "Usage::User"
  
end

app/models/usage/pattern.rb
class Usage::Pattern < ActiveRecord::Base
  attr_accessible :field_name, :model_for_pattern_id, :operator_id,
                  :owner_id, :ownership_id, :value

  # Associations
  belongs_to :operator, class_name: "Tagging::TagRuleOperator"
  belongs_to :model_for_pattern, class_name: "Crm::ModelForPattern"
  belongs_to :owner, class_name: "Usage::User"
  belongs_to :ownership, class_name: "Ownership"

  def to_scope
    datatype = Usage::User.columns_hash[self.field_name].type
    self.value = get_value_according_to_type(datatype)
    Usage::User.where("#{self.field_name} #{self.operator.name} #{self.value}")
  end

protected

  def get_value_according_to_type(datatype)
    case datatype
    when :integer
      self.value.to_i
    when :string
      self.value.to_s
    when :float
      self.value.to_f
    else
      self.value
    end
  end

end

app/models/usage/profile.rb
class Usage::Profile < ActiveRecord::Base

  include HasContactInfoStereotype
  include OwnedStereotype
  
  attr_accessible :logo, :name, :owner_id, :ownership_id
  # logo_file for mounting an uploader of carrierwave

  liquid_methods :name
  
  validates_presence_of :name
  
  has_attached_file :logo, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  # Associations
  belongs_to :ownership, :foreign_key => :ownership_id, :class_name => "Ownership"
  belongs_to :owner, :foreign_key => :owner_id, :class_name => "Usage::User"
  has_and_belongs_to_many :users, :join_table => 'usage_profiles_users', :class_name => "Usage::User", :foreign_key => :profile_id
  belongs_to :contact_info
  has_one :crm_connection, :foreign_key => :profile_id,:class_name => "Crm::Connection"
  has_many :snail_mail_messages, :class_name => "Marketing::SnailMail::Message"
  
  scope :viewables, lambda { |user|
    t = Usage::Profile.arel_table
    user_and_ascendent_ids = user.ascendent_ids.uniq
    user_and_ascendent_ids << user.id
    user.profiles.where(t[:owner_id].in(user_and_ascendent_ids).or(t[:ownership_id].eq(Ownership.find_by_value('global').id)))
  }

  scope :editables, lambda { |user|
    t = Usage::Profile.arel_table
    user_and_ascendent_ids = user.ascendent_ids.uniq
    user.profiles.where(t[:owner_id].eq(user.id).or(t[:owner_id].in(user_and_ascendent_ids).and(t[:ownership_id].in(Ownership.find_by_value('user and descendents').id))).or(t[:ownership_id].eq(Ownership.find_by_value('global').id)))
  }

  #Explicit column definitions for rspec-fire
  def name; super; end
end

app/models/usage/profiles_user.rb
class Usage::ProfilesUser < ActiveRecord::Base

  belongs_to :profile , :class_name => "Usage::Profile"
  belongs_to :user , :class_name => "Usage::User"
  attr_accessible :profile_id, :user_id
  
end

app/models/usage/sales_support_field_set.rb
class Usage::SalesSupportFieldSet < ActiveRecord::Base
  
  attr_accessible :docusign_account_id, :docusign_email, :docusign_password, :metlife_agent_id
  
  # Associations
  has_many :users
  
end

app/views/usage/users/_children.html.erb
<input type="checkbox" data-user-id="<%= children.id %>" class="permissions-user-checkbox<%= @box_id %> select-checkbox">

<%= link_to "/usage/users/personal?user_id=#{children.id}", :remote => true do %>
  <i class="icon icon-link" id = "personal-link<%=children.id%>"  ></i>
<% end %>
<%= link_to "/usage/users/impersonate?id=#{children.id}" do %>
  <i class="icon icon-beaker" id = "lead-link<%=children.id%>"  ></i>
<% end %>
<%= link_to "/usage/staff_assignment/index?tab=privileges", :remote => true do %>
  <i class="icon icon-group" id = "staff-assignment-link"  ></i>
<% end %>

<a href="javascript: void(0);" id="permission-user-select<%= children.id %>" class="permission-user-select-event ajax" data-user-id="<%= children.id %>" data-box-id="<%= @box_id %>" title="<%= children.full_name.to_s %>">
  <%= children.full_name.to_s %>
</a>
<a href="javascript: void(0);" id="make-user-parent<%= children.id %>" class="make-user-parent ajax" data-user-id="<%= children.id %>" title="Double click to make this user a parent user">
  <i class="icon icon-link"></i>
</a>
<br>

app/views/usage/users/_task.html.erb
<div class="row-fluid">
  <div class="span1">
    <a id="user-follow-up-task-link" class="ajax" data-case-id="<%= task.status.try(:case).try(:id) %>">
      <i class="icon icon-link"></i>
    </a>
  </div>
  <div class="span2">
    <%= task.task_type.try(:name) %>
  </div>
  <div class="span2">
    <%= task_type == "incomplete" ? task.due_at : task.completed_at %>
  </div>
  <div class="span2">
    <%= task.assigned_to.try(:full_name) %>
  </div>
  <div class="span2">
    <%= task.crm_connection.try(:full_name) %>
  </div>
  <div class="span2">
    <%= task.label %>
  </div>
  <div class="span1">
    <input type="checkbox" id="change-task-status-<%= task.id %>" class="user-system-task-checkbox ajax" data-id="<%= task.id%>" data-status-id="<%= task.status.try(:id)%>" <%= task.completed_at.blank? ? '' : 'checked' %>>
  </div>
</div>

app/views/usage/users/_tasks.html.erb
<input type="hidden" id="task-status-user-id" value="<%= @usage_user.id %>">

<%= render :partial => "shared/tab/agency_management", :locals => {:tab => "tasks"} %>
<div class="navbar">
  <div class="navbar-inner">
    <div class="row-fluid">
      <div class="span4">
        <h4 class="title system-management-row">To Do</h4>
      </div>
      <div class="span4">
        <%= form_tag( incomplete_tasks_usage_users_path(:user_id=>@usage_user.id, :container_id=>'user-incomplete-tasks-container'), :remote => true, :id => "user-incomplete-tasks-between-dates",
                      :class => "user-incomplete-tasks-between-dates ajax" , :method => :get, :style=>"margin: 10px 0;" ) do  %>
          <fieldset>
            <div class="control-group">
              <div class="controls">
                <div class="input-prepend">
                  <input type="hidden" name="incomplete_from_date" id="incomplete-from-date-range">
                  <input type="hidden" name="incomplete_to_date" id="incomplete-to-date-range">
                  <input type="text" name="user-incomplete-tasks-date-range-field" id="user-incomplete-tasks-date-range-field" readonly>
                  <span class="add-on"><i class="icon-calendar"></i></span>
                </div>
              </div>
            </div>
          </fieldset>
        <% end %>
      </div>
      <div class="span4" style="margin-top:10px;">
        <input class="input-medium" type="text" placeholder="Search" id="input-search-user-incomplete-tasks" style="width:150px;" value="<%= params[:search_incomplete_tasks] %>">
        <a style="margin-top: -10px;" class="btn btn-small btn-primary ajax" id="button-search-user-incomplete-tasks" type="button" >
          <i class="icon-search icon-white"></i>
        </a>
      </div>
    </div>
  </div>
</div>

<div id="user-incomplete-tasks-container">
</div>
<div style="background-color: #1B1B1B; min-height: 35px; margin: 0 0 0 0;"></div>
<div class="navbar">
  <div class="navbar-inner">
    <div class="row-fluid">
      <div class="span4">
        <h4 class="title system-management-row">Completed</h4>
      </div>
      <div class="span4">
        <%= form_tag( completed_tasks_usage_users_path(:user_id=>@usage_user.id, :container_id=>'user-completed-tasks-container'), :remote => true, :id => "user-completed-tasks-between-dates",
                      :class => "user-completed-tasks-between-dates ajax" , :method => :get, :style=>"margin: 10px 0;" ) do  %>
          <fieldset>
            <div class="control-group">
              <div class="controls">
                <div class="input-prepend">
                  <input type="hidden" name="completed_from_date" id="completed-from-date-range">
                  <input type="hidden" name="completed_to_date" id="completed-to-date-range">
                  <input type="text" name="user-completed-tasks-date-range-field" id="user-completed-tasks-date-range-field" readonly>
                  <span class="add-on"><i class="icon-calendar"></i></span>
                </div>
              </div>
            </div>
          </fieldset>
        <% end %>
      </div>
      <div class="span4" style="margin-top:10px;">
        <input class="input-medium" type="text" placeholder="Search" id="input-search-user-completed-tasks" style="width:150px;" value="<%= params[:search_completed_tasks] %>">
        <a style="margin-top: -10px;" class="btn btn-small btn-primary ajax" id="button-search-user-completed-tasks" type="button" >
          <i class="icon-search icon-white"></i>
        </a>
      </div>
    </div>
  </div>
</div>

<div id="user-completed-tasks-container">
</div>

<script>
  $(document).ready(function() {
    loadPage('user-incomplete-tasks-container', '/usage/users/incomplete_tasks?user_id=<%=@usage_user.id%>')
    loadPage('user-completed-tasks-container', '/usage/users/completed_tasks?user_id=<%=@usage_user.id%>')

    $('#user-incomplete-tasks-date-range-field').daterangepicker('change',function(start, end){
      $("#incomplete-from-date-range").val(start.toString('MMMM d, yyyy'));
      $("#incomplete-to-date-range").val(end.toString('MMMM d, yyyy'));
      $("#user-incomplete-tasks-between-dates.ajax").submit();
    });

    $('#user-completed-tasks-date-range-field').daterangepicker('change',function(start, end){
      $("#completed-from-date-range").val(start.toString('MMMM d, yyyy'));
      $("#completed-to-date-range").val(end.toString('MMMM d, yyyy'));
      $("#user-completed-tasks-between-dates.ajax").submit();
    });

  });
</script>

app/views/usage/users/_user_tasks_date_range_picker.html.erb
<%= form_tag( tasks_usage_users_path(:user_id=>@usage_user.id), :remote => true, :id => "user-#{task_type}-tasks-between-dates",
              :class => "user-#{task_type}-tasks-between-dates ajax" , :method => :get, :style=>"margin: 10px 0;" ) do  %>
  <fieldset>
    <div class="control-group">
      <div class="controls">
        <div class="input-prepend">
          <input type="hidden" name="from_date" id="from-date-range">
          <input type="hidden" name="to_date" id="to-date-range">
          <input type="text" name="user-<%= task_type %>-tasks-date-range-field" id="user-<%= task_type %>-tasks-date-range-field" readonly>
          <span class="add-on"><i class="icon-calendar"></i></span>
        </div>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/usage/users/assign_agent.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
  <h3>Select Agent</h3>
</div>
<div class="modal-body">
  <input id="mass-assigning-agent" class="ajax" type="text" data-autocomplete="/usage/users/autocomplete_users_first_name">
</div>

app/views/usage/users/assign_profile.js.erb
$('#assign-profile-modal-pop-up').modal('hide');
$('#flash-container').html("<%= @msg %>");

app/views/usage/users/index.html.erb
<%= render :partial => "index" %>

app/views/usage/users/l_and_c.js.erb
$( "#main-container" ).html( "<%= escape_javascript( render( :partial => "l_and_c" ) ) %>" );

app/views/usage/users/memberships.js.erb
$( "#main-container" ).html( "<%= escape_javascript( render( :partial => "memberships" ) ) %>" );

app/views/usage/users/new.html.erb
<%= render :partial => "new" %>

app/views/usage/users/new.js.erb
$("#main-container").html( "<%= escape_javascript( render( :partial => "new" ) ) %>" );

app/views/usage/users/personal.js.erb
$("#main-container").html( "<%= escape_javascript( render( :partial => "personal" ) ) %>" );

app/views/usage/users/update_agent_field_set.js.erb
$("#suspension_status_<%= @usr.id %>").html("<%= escape_javascript(render :partial => 'temporary_suspension', :locals => {:ch => @usr} )%>");
$('#flash-container').html('Successfully updated');
$("#field_set_premium_limit_<%= @usr.id %>").val(<%= @usr.agent_field_set.premium_limit %>);

app/views/usage/users/update_usage_license.js.erb
$( "#main-container" ).html( "<%= escape_javascript( render( :partial => "l_and_c" ) ) %>" );